#!/bin/bash
case "$1" in 
	cpu)
		lscpu
	;;
	memory)
		free
		;;
	*"--version"*)
		echo "v0.1.0"
		;;
	*)
esac
case "$2 + $3" in
	create)
		useradd $3
		;;
	list)
		cut -d: -f1 /etc/passwd
		;;
	list | *"--sudo-only"*)
		cat /etc/group | grep sudo
		;;
	
	*)
esac
case "$1+$2" in
	file | *"getinfo"*)
		#echo "test"
		ls -l -F $3
		;;
	*)
esac


